### ISSUE TITLE
ISPs manually blocking routes to https://invalid.rpki.cloudflare.com instead of implementing RPKI

### ISSUE THREAD

**Issue by carumusan** [cloudflare/isbgpsafeyet.com#105]
Bad routes should be rotated frequently to mitigate ISPs attempting to cover this up. A&A are doing this already.

**Comment by lspgn** [comment]
Looks like TekSavvy (CA) does it too. They blackholed the packets going to the IPs (not even rejecting the route).

**Comment by lspgn** [comment]
AS4760 Netvigator Hong Kong may have dropped the prefix too.

**Comment by lspgn** [comment]
MyRepublic is likely hijacking the prefix and null route it per RIPE Atlas probes

![Screen Shot 2020-04-22 at 3 54 20 PM](https://user-images.githubusercontent.com/27725238/80046650-0de63780-84c0-11ea-8e1e-e38e3035b107.png)
