### ISSUE TITLE
Add Proximus (BE) as unsafe

### ISSUE THREAD

**Issue by Wiggum127** [cloudflare/isbgpsafeyet.com#140]
Results of telco provider Proximus as unsafe:

Your ISP (Proximus, AS5432) does not implement BGP safely. It should be using RPKI to protect the Internet from BGP hijacks.

Details
fetch https://valid.rpki.cloudflare.com
correctly accepted valid prefixes

fetch https://invalid.rpki.cloudflare.com
incorrectly accepted invalid prefixes

**Comment by kroeckx** [comment]
This seems to have been fixed in 23ff789ce33c59f17717d4fb8401cbb0d5fc0822
