### ISSUE TITLE
Document operators.csv rank to README

### ISSUE THREAD

**Issue by betelgeuse** [cloudflare/isbgpsafeyet.com#263]
To make it easier to contribute, it would be useful to document what the rank column in operators.csv means. Basically what it should be set to for new contributions.

**Comment by diegocanton** [comment]
https://asrank.caida.org/

**Comment by lspgn** [comment]
Hi @betelgeuse,
I added a contribute file which explains it :) 
https://github.com/cloudflare/isbgpsafeyet.com/blob/master/CONTRIBUTING.md

Thank you for raising the issue
Feel free to re-open if you have more questions
