### ISSUE TITLE
Deployed RPKI already, Please help to advise the next steps we should follow

### ISSUE THREAD

**Issue by RaeHoPY** [cloudflare/isbgpsafeyet.com#453]
Dear Support,
I'm Rae of HKIX (Hong Kong Internet eXchange). 

HKIX(AS4635) supports RPKI on HKIX Route Servers starting from mid-Jun 2020 in order to enhance routing security. (deployed RPKI filtering and drops invalid prefixes). 

For Details, Please find the announcement of RPKI on HKIX website. 
https://www.hkix.net/hkix/route-policy.htm

I was wondering if could you help to add us into https://isbgpsafeyet.com/.  Would you mind advising us the next steps? Thanks.

Regards,
Rae
HKIX

**Comment by lspgn** [comment]
Hi Rae, I made a PR https://github.com/cloudflare/isbgpsafeyet.com/pull/454.
At the moment, we don't add the IX in the list (we need to figure out the ranking). I made the "latest updates" to the 7th.
Will merge if its ok to you.

**Comment by RaeHoPY** [comment]
Dear Ispgn,
Thanks a lot for your reply.

Is it possible if adding HKIX update information on the page (https://isbgpsafeyet.com/) like the below. Thanks. Rae

Latest updates
July 6, 2020 – GR-IX, the Greek Internet Exchange, is now dropping RPKI invalids on their route servers (source)

**Comment by lspgn** [comment]
I merged. Let me know if you have more questions.

**Comment by RaeHoPY** [comment]
> I merged. Let me know if you have more questions.

Prefect. Thanks a lot for your kind help. Rae

**Comment by RaeHoPY** [comment]
Would you mind adding (deployed RPKI filtering and drops invalid prefixes) in latest update? Thanks Rae
