### ISSUE TITLE
Please update the Latest updates content for AS4635

### ISSUE THREAD

**Issue by RaeHoPY** [cloudflare/isbgpsafeyet.com#457]
Dear Support,
Hello, Thanks a lot for updating AS4635 on the list. 
**Latest updates
August 7, 2020 - HKIX, an Internet Exchange in Hong Kong deployed RPKI validation on all its member sessions.** 

Would you mind mentioning **and is now dropping RPKI invalids on their route servers** in the latest update? 
August 7, 2020 - HKIX, an Internet Exchange in Hong Kong deployed RPKI validation on all its member sessions **and is now dropping RPKI invalids on their route servers**.

Thanks a lot.
Rae
HKIX

**Comment by lspgn** [comment]
Updated. Closing the ticket.
