### ISSUE TITLE
Add Shaw (AS6327) Twitter Handle

### ISSUE THREAD

**Issue by capitalg** [cloudflare/isbgpsafeyet.com#51]
I tested my ISP, tweeted about it, and noticed that they didn't get @'d in the tweet. So I @'d @eastdakota and Matthew recommended that I submit a PR. And the contributing guidelines told me to create an issue before submitting a PR.. so here we are 😊 

https://twitter.com/realGurkaran/status/1251206889121050624

**Comment by jejenone** [comment]
Thanks! We'll be accepting contributions starting next week.

**Comment by anazz20** [comment]
Same with my ISP, Charter/Spectrum.
https://twitter.com/BeforeZo/status/1251790416300703746?s=19
