### ISSUE TITLE
Add suddenlink communications as unsafe

### ISSUE THREAD

**Issue by larson-carter** [cloudflare/isbgpsafeyet.com#55]
I have tested my ISP, I also tweeted about it.

It needs to be added as unsafe!

**Comment by marcoacmaia** [comment]
Hello
Maybe put on Pull Requests area, where are  so many others

**Comment by larson-carter** [comment]
@marcoacmaia No, I can add it here if I want too. I don't want to open a PR since that will be outstanding on my side. If someone from cloudflare wants to make a PR and merge it they can.
