### ISSUE TITLE
Run BGP check on a Headless/Linux server?

### ISSUE THREAD

**Issue by r8u** [cloudflare/isbgpsafeyet.com#601]
Is there a CLI tool that runs the same test as isbgpsafeyet.com?

**Comment by lspgn** [comment]
Hello,
Afaik there is no all in one CLI but you can try reaching https://invalid.rpki.cloudflare.com and https://valid.rpki.cloudflare.com

Example:
curl https://invalid.rpki.cloudflare.com
If it replies, your network is accepting invalids.
