### ISSUE TITLE
Verizon might have fixed their issue(s) ?

### ISSUE THREAD

**Issue by gabeio** [cloudflare/isbgpsafeyet.com#675]
<img width="1864" alt="Screenshot 2023-03-16 at 16 24 31" src="https://user-images.githubusercontent.com/643410/225745115-73a3f858-13b7-4a5c-b47c-6de567981b7d.png">

I'm dubious but according to your own website it seems Verizon might have fixed their problem?

**Comment by digizeph** [comment]
It's possible that the started deploying RPKI invalid filtering partially. However other data sources indicates that the filtering rate is still low (<10% low). See APNIC's test results for AS701 as an example https://stats.labs.apnic.net/rpki/AS701

![image](https://user-images.githubusercontent.com/659667/225960250-01c52b20-5bb0-45e2-9554-cf8ca56dd23d.png)

**Comment by gabeio** [comment]
I figured it might not be the whole thing thanks!
