### ISSUE TITLE
Charter is duplicated

### ISSUE THREAD

**Issue by theone-net** [cloudflare/isbgpsafeyet.com#708]
![charter](https://github.com/cloudflare/isbgpsafeyet.com/assets/139057465/6caf4c21-f0df-4e17-9489-cef6b98d4f25)

**Comment by digizeph** [comment]
They are different networks, both under Charter but with different AS numbers:
<img width="1347" alt="Screenshot 2023-09-17 at 7 46 36 PM" src="https://github.com/cloudflare/isbgpsafeyet.com/assets/659667/428f6a99-16e4-49c1-b478-6ee1c8777876">

- 11351: https://radar.cloudflare.com/routing/as11351
- 12271:https://radar.cloudflare.com/routing/as12271

Maybe renaming them to  `Charter (Northeast)` and `Charter (NYC)` would help.

**Comment by theone-net** [comment]
Ah, ok! I didn't see that, thanks!
