### ISSUE TITLE
Cloudflare WARP not safe

### ISSUE THREAD

**Issue by AnimMouse** [cloudflare/isbgpsafeyet.com#744]
![Screenshot 2024-05-28 at 19-29-32 Is BGP safe yet · Cloudflare](https://github.com/cloudflare/isbgpsafeyet.com/assets/40349541/92312df0-2417-414f-a032-fe3b66e071b5)
```json
{"status":"valid","asn":13335,"name":"Cloudflare","blackholed":false}
```

**Comment by digizeph** [comment]
<img width="742" alt="image" src="https://github.com/cloudflare/isbgpsafeyet.com/assets/659667/0efc47ad-bd03-47c0-a7de-b448220826da">

**Comment by AnimMouse** [comment]
I'm currently using Cloudflare WARP as an IPv4 tunnel for my IPv6 only VPS. I think this special case detection #10 should have been able to work even if `https://valid.rpki.cloudflare.com/cdn-cgi/trace` gives not a Cloudflare IP.
