### ISSUE TITLE
AS33915 is safe while this repo suggests otherwise

### ISSUE THREAD

**Issue by AlexStorm1313** [cloudflare/isbgpsafeyet.com#747]
![image](https://github.com/cloudflare/isbgpsafeyet.com/assets/5901188/f9d52b68-5408-4926-954f-74c5a0ce823d)
Signed and filtering: https://stats.labs.apnic.net/rpki/AS33915

**Comment by digizeph** [comment]
Thank you for the ticket and PR. We updated AS33915 to safe category as it now does both signing and filtering.
